#!/usr/bin/env python3
"""
Script tự động khởi tạo template Streamlit Modular Toolbox
Chạy lệnh: python setup_project.py
"""
import os
from pathlib import Path

FILES = {
    '.streamlit/config.toml': '[server]\nheadless = true\nenableCORS = false\nenableXsrfProtection = true\n\n[theme]\nbase = "dark"\nprimaryColor = "#2563EB"\nbackgroundColor = "#0F172A"\nsecondaryBackgroundColor = "#1E293B"\ntextColor = "#F8FAFC"\nfont = "sans serif"\n',
    '.streamlit/secrets.toml.example': '# File mau secrets - Doi ten thanh secrets.toml va dien thong tin\n# KHONG COMMIT secrets.toml LEN GIT!\n\n[app]\napp_password = "admin_password_here"\n\n[google_sheets]\ncredentials_json_path = "path/to/credentials.json"\nspreadsheet_id = "your_spreadsheet_id_here"\n\n[apis]\ndata_api_key = "your_api_key_here"\n',
    'core/__init__.py': '"""Ha tang & shared services dung chung."""\n',
    'core/config.py': 'import os\nimport streamlit as st\n\ndef get_secret(key: str, default: str = "") -> str:\n    """Lay gia tri tu st.secrets hoac bien moi truong."""\n    try:\n        keys = key.split(".")\n        val = st.secrets\n        for k in keys:\n            val = val[k]\n        return str(val)\n    except Exception:\n        return os.environ.get(key, default)\n',
    'core/db.py': '"""Ket noi Google Sheets / Database."""\nimport streamlit as st\n\n@st.cache_resource\ndef init_db_connection():\n    """Khoi tao connection pool hoac gspread client dung chung."""\n    # Vi du:\n    # import gspread\n    # gc = gspread.service_account(filename="credentials.json")\n    # return gc\n    return None\n',
    'core/logger.py': 'import logging\n\nlogging.basicConfig(\n    level=logging.INFO,\n    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",\n    datefmt="%Y-%m-%d %H:%M:%S"\n)\n\ndef get_logger(name: str):\n    return logging.getLogger(name)\n',
    'common/__init__.py': '"""Shared UI components & utilities."""\n',
    'common/styles.py': 'import streamlit as st\n\ndef apply_custom_styles():\n    """Custom CSS bo sung cho Streamlit UI."""\n    st.markdown("""\n        <style>\n        .metric-card {\n            background-color: #1E293B;\n            border: 1px solid #334155;\n            border-radius: 8px;\n            padding: 16px;\n            margin-bottom: 12px;\n        }\n        .stMetric {\n            background: rgba(30, 41, 59, 0.5);\n            padding: 10px 14px;\n            border-radius: 6px;\n            border: 1px solid #334155;\n        }\n        </style>\n    """, unsafe_allow_html=True)\n',
    'common/helpers.py': 'import pandas as pd\n\ndef export_df_to_excel_csv(df: pd.DataFrame) -> bytes:\n    """Xuat DataFrame sang CSV UTF-8 co BOM de mo tren Excel khong loi font."""\n    return df.to_csv(index=False, encoding="utf-8-sig").encode("utf-8-sig")\n\ndef format_currency_vnd(amount: float) -> str:\n    """Format so sang dinh dang VND."""\n    try:\n        return f"{amount:,.0f} ₫".replace(",", ".")\n    except (ValueError, TypeError):\n        return "0 ₫"\n\ndef format_percent(val: float, decimals: int = 2) -> str:\n    """Format so sang phan tram."""\n    try:\n        return f"{val * 100:.{decimals}f}%"\n    except (ValueError, TypeError):\n        return "0.00%"\n',
    'tools/tool_investment/__init__.py': '"""Tool Quan ly & Phan bo Danh muc (VAM-style)."""\n',
    'tools/tool_investment/engine.py': '"""Logic tinh toan thuan Python cho Investment (khong phu thuoc Streamlit)."""\nimport pandas as pd\n\ndef compute_vam_portfolio_summary(data: list = None) -> dict:\n    """Tinh toan tong gia tri danh muc va tin hieu rebalance."""\n    if not data:\n        return {\n            "total_value": 1250000000,\n            "cash_ratio": 0.10,\n            "risk_score": 0.62,\n            "rebalance_action": "Toi uu hoa ty trong"\n        }\n    df = pd.DataFrame(data)\n    total_val = df["market_value"].sum() if "market_value" in df.columns else 0\n    return {\n        "total_value": total_val,\n        "cash_ratio": 0.15,\n        "risk_score": 0.55,\n        "rebalance_action": "Giu nguyen ty trong"\n    }\n',
    'tools/tool_investment/view.py': 'import streamlit as st\nimport pandas as pd\nfrom common.helpers import format_currency_vnd, export_df_to_excel_csv\nfrom tools.tool_investment.engine import compute_vam_portfolio_summary\n\ndef render_investment_tool():\n    st.header("📈 Phân bổ Danh mục & Định giá (VAM)")\n    st.caption("Quản trị danh mục, tính toán Composite Valuation Index và tín hiệu rebalance.")\n    \n    tab1, tab2, tab3 = st.tabs(["📊 Tổng quan & Tỷ trọng", "⚙️ Cập nhật Dữ liệu", "📋 Export & Logs"])\n    \n    with tab1:\n        summary = compute_vam_portfolio_summary()\n        col1, col2, col3 = st.columns(3)\n        col1.metric("Tổng tài sản ước tính", format_currency_vnd(summary["total_value"]), "+1.8%")\n        col2.metric("Chỉ số định giá", f"{summary[\'risk_score\']:.2f}", "-0.04")\n        col3.metric("Tín hiệu Rebalance", summary["rebalance_action"])\n        \n        st.divider()\n        st.subheader("Phân bổ tài sản hiện tại")\n        sample_df = pd.DataFrame({\n            "Mã / Loại tài sản": ["Cổ phiếu (Index ETF)", "Trái phiếu / Tiết kiệm", "Crypto (BTC/BNB)", "Tiền mặt"],\n            "Tỷ trọng mục tiêu (%)": [45, 30, 15, 10],\n            "Tỷ trọng thực tế (%)": [48, 28, 14, 10],\n            "Độ lệch (%)": ["+3%", "-2%", "-1%", "0%"]\n        })\n        st.dataframe(sample_df, use_container_width=True)\n\n    with tab2:\n        st.subheader("Cập nhật tham số & giá thị trường")\n        with st.form("update_market_data"):\n            st.text_input("Tải lại API hoặc nhập mã danh mục:")\n            submitted = st.form_submit_button("Đồng bộ dữ liệu")\n            if submitted:\n                st.success("Đã đồng bộ thông số thị trường thành công!")\n\n    with tab3:\n        st.subheader("Xuất báo cáo dữ liệu")\n        csv_bytes = export_df_to_excel_csv(sample_df)\n        st.download_button(\n            label="📥 Tải CSV báo cáo (UTF-8 BOM)",\n            data=csv_bytes,\n            file_name="portfolio_allocation.csv",\n            mime="text/csv"\n        )\n',
    'tools/tool_automation/__init__.py': '"""Tool Tac vu Tu dong hoa."""\n',
    'tools/tool_automation/engine.py': '"""Logic xu ly backend tu dong hoa."""\ndef get_service_status():\n    return {\n        "webhook_receiver": "Active 🟢",\n        "cron_sync": "Running (Next run in 25m) 🟡",\n        "cloud_sync": "Idle ⚪"\n    }\n',
    'tools/tool_automation/view.py': 'import streamlit as st\nfrom tools.tool_automation.engine import get_service_status\n\ndef render_automation_tool():\n    st.header("⚡ Tác vụ Tự động hóa & Hệ thống")\n    st.caption("Giám sát trạng thái bot, background cronjobs và các luồng tự động.")\n    \n    statuses = get_service_status()\n    \n    col1, col2, col3 = st.columns(3)\n    col1.metric("Webhook Receiver", statuses["webhook_receiver"])\n    col2.metric("Cron Sync Job", statuses["cron_sync"])\n    col3.metric("Cloud Storage Sync", statuses["cloud_sync"])\n    \n    st.divider()\n    st.subheader("Trigger tác vụ thủ công")\n    if st.button("🚀 Chạy kiểm tra kết nối hệ thống"):\n        with st.spinner("Đang ping tới các services..."):\n            st.success("Tất cả các dịch vụ đang hoạt động ổn định!")\n',
    'app.py': 'import streamlit as st\nfrom common.styles import apply_custom_styles\nfrom tools.tool_investment.view import render_investment_tool\nfrom tools.tool_automation.view import render_automation_tool\n\nst.set_page_config(\n    page_title="Personal Toolbox",\n    page_icon="🛠️",\n    layout="wide",\n    initial_sidebar_state="expanded"\n)\n\ndef main():\n    apply_custom_styles()\n    \n    st.sidebar.title("🎛️ Personal Toolbox")\n    st.sidebar.caption("Workspace Platform")\n    \n    tools_registry = {\n        "📈 Quản lý & Định giá VAM": render_investment_tool,\n        "⚡ Tác vụ & Tự động hóa": render_automation_tool,\n    }\n    \n    selected_tool = st.sidebar.radio(\n        "Lựa chọn công cụ:",\n        options=list(tools_registry.keys()),\n        index=0\n    )\n    \n    st.sidebar.divider()\n    st.sidebar.markdown("**Trạng thái hệ thống:** 🟢 Sẵn sàng")\n    \n    # Hiển thị tool được chọn\n    tools_registry[selected_tool]()\n\nif __name__ == "__main__":\n    main()\n',
    'requirements.txt': 'streamlit>=1.35.0\npandas>=2.1.0\nnumpy>=1.26.0\nplotly>=5.20.0\nrequests>=2.31.0\nopenpyxl>=3.1.0\ngspread>=6.0.0\n',
    '.gitignore': '# Python\n__pycache__/\n*.py[cod]\n*$py.class\n*.so\n.Python\nenv/\nvenv/\n.venv/\n\n# Streamlit\n.streamlit/secrets.toml\n\n# Logs & Data\n*.log\ndata/\n*.csv\n*.xlsx\n.DS_Store\n',
    'README.md': '# Personal Toolbox Platform (Streamlit)\n\nNền tảng tích hợp các công cụ làm việc cá nhân, thiết kế theo kiến trúc module hóa độc lập, chuẩn layout tương tự VAM.\n\n## Cấu trúc dự án\n- `app.py`: Entry point chính quản lý router và navigation sidebar.\n- `core/`: Các module dùng chung (DB, logger, config, secrets).\n- `common/`: Giao diện chung (CSS styles, export CSV UTF-8 BOM, formatters).\n- `tools/`: Mỗi tool là một thư mục con riêng biệt với `engine.py` (logic tính toán) và `view.py` (giao diện Streamlit).\n\n## Hướng dẫn cài đặt & khởi chạy\n```bash\n# 1. Tạo môi trường ảo\npython -m venv venv\nsource venv/bin/activate  # Trên Linux/macOS\n# venv\\Scripts\\activate  # Trên Windows\n\n# 2. Cài đặt thư viện\npip install -r requirements.txt\n\n# 3. Tạo file secrets từ mẫu\ncp .streamlit/secrets.toml.example .streamlit/secrets.toml\n\n# 4. Khởi chạy app\nstreamlit run app.py\n```\n',
}

def build_structure(base_dir="."):
    print("🚀 Bắt đầu khởi tạo cấu trúc dự án Streamlit Toolbox...")
    base_path = Path(base_dir)
    for file_rel_path, content in FILES.items():
        p = base_path / file_rel_path
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"  ✓ Đã tạo: {file_rel_path}")
    print("\n🎉 Khởi tạo hoàn tất! Bạn có thể bắt đầu với:")
    print("  1. pip install -r requirements.txt")
    print("  2. cp .streamlit/secrets.toml.example .streamlit/secrets.toml")
    print("  3. streamlit run app.py\n")

if __name__ == "__main__":
    build_structure()